# =============================================================================
# Process and Save Synthetic Data for bhfvar Package
#
# This script reads the synthetic data generated by Python and saves it
# as package data in .rda format.
#
# Author: JoonHo Lee (jlee296@ua.edu)
# Date: 2025-01-24
# =============================================================================

# Read the synthetic data
bhf_synthetic_data <- read.csv("data-raw/bhf_synthetic_data.csv",
                                stringsAsFactors = FALSE)

# Verify structure
str(bhf_synthetic_data)

# Summary
cat("\n=== Synthetic Data Summary ===\n")
cat("Observations:", nrow(bhf_synthetic_data), "\n")
cat("States:", length(unique(bhf_synthetic_data$state)), "\n")
cat("Strata:", length(unique(bhf_synthetic_data$stratum)), "\n")
cat("PSUs:", length(unique(bhf_synthetic_data$psu)), "\n")
cat("Overall proportion:", mean(bhf_synthetic_data$has_subsidy), "\n")

# Save as package data
usethis::use_data(bhf_synthetic_data, overwrite = TRUE)

# Also read state truth for verification (not exported)
bhf_state_truth <- read.csv("data-raw/state_truth.csv",
                             stringsAsFactors = FALSE)

# Save for internal use
usethis::use_data(bhf_state_truth, internal = TRUE, overwrite = TRUE)

cat("\nData saved successfully!\n")
